apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrap-api-deployment
spec:
  selector:
    matchLabels:
      app: scrap-api
  replicas: 2
  template:
    metadata:
      labels:
        app: scrap-api
    spec:
      containers:
        - name: scrap-api
          image: fathhhhh/gapscrap:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: scrap-api-service
spec:
  selector:
    app: scrap-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
